CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR (255) UNIQUE NOT NULL,
    password VARCHAR (255) NOT NULL,
    first_name VARCHAR (255) NOT NULL,
    last_name VARCHAR (255) NOT NULL,
    phone_number VARCHAR (255) UNIQUE NOT NULL,
    PRIMARY KEY (id));


INSERT INTO users (email,password,first_name ,last_name ,phone_number )
VALUES (
           'admin@gmail.com',
           '$2a$12$JGcWpIWbaMGiZX07pVmbd.PYeVMPbzMxMZ8OPT7aEMkltkyRKEeYa',
           'admin',
           'adminov',
           '+375291234567'
       );