CREATE TABLE IF NOT EXISTS resume (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name_resume VARCHAR (255) NOT NULL,
    description VARCHAR (255) NOT NULL,
    PRIMARY KEY (id));

INSERT INTO resume (name_resume, description)
VALUES (
           'builder-engineer',
           'about me'
       );